# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c605d78b34e5c4614aa8b4305f9744c95c1babe65570429f071c0e6eda731c58c124c7c53795fc476a4b1af6c9050d3d9a8270cf5d505014056f495ccc5bf31

test:
  secret_key_base: 8ade91a5c1915ea74738df00aaccea40c42ac82da488ad2c26897a70ffb5ef750b3880acaf631620fd83f3bdd99a77989e3c981a0d07cb7b825b9f5337325a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
